#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${ROOT_DIR}"

# Arrays for mount options
MOUNTS_RW=()
MOUNTS_RO=()

function show_usage() {
  cat <<EOF
Usage: ./deploy.sh <build|cleanup> [OPTIONS]

Commands:
  build     Build and deploy the containers
  cleanup   Stop containers and remove images

Options:
  --mount-rw=PATH    Mount host PATH as read-write in container (can be repeated)
  --mount-ro=PATH    Mount host PATH as read-only in container (can be repeated)
  --help             Show this help message

Examples:
  ./deploy.sh build
  ./deploy.sh build --mount-rw=/home/user/projects --mount-ro=/data/reference
  ./deploy.sh cleanup
EOF
}

# Parse arguments
ACTION=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    build|cleanup)
      ACTION="$1"
      shift
      ;;
    --mount-rw=*)
      MOUNTS_RW+=("${1#--mount-rw=}")
      shift
      ;;
    --mount-ro=*)
      MOUNTS_RO+=("${1#--mount-ro=}")
      shift
      ;;
    --help|-h)
      show_usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      show_usage
      exit 1
      ;;
  esac
done

if [[ -z "${ACTION}" ]]; then
  show_usage
  exit 1
fi

function read_config_value() {
  local key="$1"
  python3 - <<PY
import sys
import yaml

with open("config/api.yaml", "r", encoding="utf-8") as handle:
    config = yaml.safe_load(handle)

value = config
for part in "${key}".split("."):
    value = value.get(part, {})

if isinstance(value, dict):
    sys.exit("Missing key: ${key}")

print(value)
PY
}

function render_ui_config() {
  cat > src/web_terminal_client/public/config.yaml <<EOF
server:
  port: ${WEB_PORT}
  host: "0.0.0.0"

api:
  base_url: "http://localhost:${API_PORT}"

ui:
  max_output_lines: 1000
  auto_scroll: true
EOF
}

function generate_compose_override() {
  # Generate docker-compose.override.yml with extra mounts if any were specified
  local override_file="docker-compose.override.yml"
  
  if [[ ${#MOUNTS_RW[@]} -eq 0 && ${#MOUNTS_RO[@]} -eq 0 ]]; then
    # No mounts specified, remove override file if exists
    rm -f "${override_file}"
    return
  fi

  cat > "${override_file}" <<EOF
# Auto-generated by deploy.sh - do not edit manually
services:
  agentum-api:
    volumes:
EOF

  # Add read-write mounts
  for mount in "${MOUNTS_RW[@]+"${MOUNTS_RW[@]}"}"; do
    if [[ -n "${mount}" ]]; then
      # Normalize path for cross-platform compatibility
      local abs_path
      abs_path="$(cd "${mount}" 2>/dev/null && pwd)" || abs_path="${mount}"
      local basename
      basename="$(basename "${abs_path}")"
      echo "      - ${abs_path}:/mounts/${basename}:rw" >> "${override_file}"
    fi
  done

  # Add read-only mounts
  for mount in "${MOUNTS_RO[@]+"${MOUNTS_RO[@]}"}"; do
    if [[ -n "${mount}" ]]; then
      local abs_path
      abs_path="$(cd "${mount}" 2>/dev/null && pwd)" || abs_path="${mount}"
      local basename
      basename="$(basename "${abs_path}")"
      echo "      - ${abs_path}:/mounts/${basename}:ro" >> "${override_file}"
    fi
  done

  echo "Generated ${override_file} with custom mounts."
}

function check_services() {
  local missing=0
  local running
  running="$(docker compose ps --status running --services || true)"
  for svc in agentum-api agentum-web; do
    if ! grep -q "${svc}" <<<"${running}"; then
      echo "Service not running: ${svc}"
      missing=1
    fi
  done
  return "${missing}"
}

if [[ "${ACTION}" == "cleanup" ]]; then
  docker compose down --remove-orphans
  if docker images --format '{{.Repository}}:{{.Tag}}' | grep -q '^agentum:'; then
    docker images --format '{{.Repository}}:{{.Tag}}' \
      | grep '^agentum:' \
      | xargs -r docker image rm
  fi
  rm -f docker-compose.override.yml
  echo "Cleanup complete."
  exit 0
fi

API_PORT="$(read_config_value 'api.external_port')"
WEB_PORT="$(read_config_value 'web.external_port')"

render_ui_config
generate_compose_override

IMAGE_TAG="deploy-$(date +%Y%m%d%H%M%S)"
BACKUP_ENV="$(mktemp)"
ROLLBACK_ENV=0

cleanup() {
  if [[ "${ROLLBACK_ENV}" -eq 1 && -s "${BACKUP_ENV}" ]]; then
    cp "${BACKUP_ENV}" .env
    docker compose up -d --remove-orphans || true
  fi
  rm -f "${BACKUP_ENV}"
}

trap cleanup EXIT

if [[ -f .env ]]; then
  cp .env "${BACKUP_ENV}"
fi

echo "Building image agentum:${IMAGE_TAG}..."
docker build -t "agentum:${IMAGE_TAG}" .

ROLLBACK_ENV=1
cat > .env <<EOF
AGENTUM_IMAGE_TAG=${IMAGE_TAG}
AGENTUM_API_PORT=${API_PORT}
AGENTUM_WEB_PORT=${WEB_PORT}
EOF

echo "Starting containers with tag ${IMAGE_TAG}..."
docker compose up -d --remove-orphans

if ! check_services; then
  echo "Deployment failed, rolling back."
  exit 1
fi

ROLLBACK_ENV=0
echo "Deployment complete."
